### ISSUE TITLE
UICollectionSectionFooter

### ISSUE THREAD

**Issue by luowen1991** [devxoul/UICollectionViewFlexLayout#3]
when I register view for UICollectionElementKindSectionFooter,it don't work

**Comment by devxoul** [comment]
How did you try?

**Comment by luowen1991** [comment]
static let footerView = ReusableView<LiveListFooterView>(nibName:"LiveListFooterView")
collectionView.register(Reusable.footerView, kind: UICollectionElementKindSectionFooter)
case UICollectionElementKindSectionFooter:
            let view = collectionView.dequeue(Reusable.footerView, kind: kind, for: indexPath)
            return view

I guess it maybe I can't find the method to set footer size in the UICollectionViewDelegateFlowLayout

**Comment by luowen1991** [comment]
static let footerView = ReusableView<LiveListFooterView>(nibName:"LiveListFooterView")
collectionView.register(Reusable.footerView, kind: UICollectionElementKindSectionFooter)
case UICollectionElementKindSectionFooter:
let view = collectionView.dequeue(Reusable.footerView, kind: kind, for: indexPath)
return view

I guess it maybe I can't find the method to set footer size in the UICollectionViewDelegateFlowLayout

**Comment by luowen1991** [comment]
static let footerView = ReusableView(nibName:"LiveListFooterView")
collectionView.register(Reusable.footerView, kind: UICollectionElementKindSectionFooter)
case UICollectionElementKindSectionFooter:
let view = collectionView.dequeue(Reusable.footerView, kind: kind, for: indexPath)
return view

I guess it maybe I can't find the method to set footer size in the UICollectionViewDelegateFlexLayout

**Comment by devxoul** [comment]
Header and footer is not supported, yet.

**Comment by uzman** [comment]
Is there any update for footer and header?
